server:
    port: 8080
    servlet:
        encoding:
            force-response=true:
    error:
        include-message: always
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

---

spring:
    datasource:
        jdbc-url: jdbc:mysql://localhost:3306/wanted-preonboarding-challenge-backend-20
        username: taylor
        password: pass
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

    jwt:
        key: 08d9f6bd6f2f76186106617f85c808c8646707145c91c5054007c5e24925945f
        expiration: 3600000
